# Darius-Florentin Neatu <neatudarius@gmail.com>
# Copyright 2018

# Exemplu de Makefile pentru tema

# tag-uri obligatorii (nume + comportament identic)
# build    => compileaza toata tema 
#             (ATENTIE! E important - NU compilati in tag-urile de run. Sesizati?)
# run-p$ID => ruleaza problema cu ID-ul specificat (1, 2, 3, 4)
# clean    => sterge toate fisierele generate

# restul este la alegerea studentului
# TODO

# nume necesar (build)

build: 
	g++ -std=c++11 -Wall -Wextra -lm bani.cpp -o bani
	g++ -std=c++11 -Wall -Wextra -lm gard.cpp -o gard
	g++ -std=c++11 -Wall -Wextra -lm bomboane.cpp -o bomboane
run-p1:		 # nume necesar
	./bani
run-p2:      # nume necesar
	./gard 
run-p3:      # nume necesar 
	./bomboane
run-p4:      # nume necesar 
clean:
	rm -f bani gard bomboane	 # nume necesar
